version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports: 
      - 2368:2368
    restart: always
    depends_on:
      - "db"
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ghost-network
    environment: 
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-data:

networks:
  ghost-network:
